---
title: "Figure 7:  updated survival analyses"
site: workflowr::wflow_site
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r packages, include=FALSE}
library(grid)
library(ggplot2)
library(openxlsx)
library(survival)
library(survminer)
library(data.table)
library(cowplot)
library(tidyverse)
library(gridExtra)
library(here)
```


```{r inputs,  echo=FALSE, include=FALSE}
# load functions
source(here("code", "misc", "survival_functions.R"))
```



# Panels A - B: IO only
## Panel A : Patients recieving IO in any line of therapy
## Panel B : Patients recieving IO in 1st line of therapy

Comparing KRAS G12C to co-mutation of KRAS G12C and other genes

```{r survival_data_io,  echo=FALSE, include=FALSE}
## use hotspot mutations for Chromatin Reg pathway and all mutations for KEAP1, NTRK3
os <- read_tsv(here("data","os_annotated.tsv"),
               show_col_types=FALSE)
therapy_ <- therapy <-"IO ; IO + chemo_IO"
os <- os %>%
    filter(flag_KRAS_G12C == 1 ) %>%
      mutate(`KRAS_G12C~AMER1` = ifelse(flag_KRAS_G12C == 1 & flag_AMER1 == 1, 1 ,0)) %>%
      mutate(`KRAS_G12C~STK11` = ifelse(flag_KRAS_G12C == 1 & flag_STK11 == 1, 1 ,0)) %>%
    mutate(`KRAS_G12C~TP53_hotspot` = ifelse(flag_KRAS_G12C == 1 & flag_TP53_hotspot == 1, 1 ,0)) %>%
  mutate(`KRAS_G12C~PIK3CA` = ifelse(flag_KRAS_G12C == 1 & flag_PIK3CA == 1, 1 ,0)) %>%
    dplyr::rename(therapy = Survival_Analyses)


variable.list <- colnames(os)[c(81:84)]
ix <- c(grep("STK11", variable.list),
        grep("PIK3CA", variable.list))
variable.list <- variable.list[ix]
parseLabel <- function(x){
    group1 <- strsplit(x, "~")[[1]][1] %>%
        str_replace("_", " ")
    group2 <- str_replace(x, "~", " / ") %>%
        str_replace("_", " ")
    labs <- c(group1, group2)
    labs
}
glist <- vector("list", 2)
panel_label <- LETTERS[1:2]

os.df <- filter(os, therapy %in% therapy_) %>%
           select(Overal_survival_months,
           Overall_survival_censor,
           COHORT_CD_DESC,
           all_of(variable.list))

os.df.list <-list(os.df ,
                  os.df %>%
                      filter( COHORT_CD_DESC == "Patients in the Broad 1st Line of Therapy"))

```

```{r surv_grobs}

glist <- vector("list", length(variable.list))

for (i in seq_along(variable.list)){
    variable <- variable.list[i]
    labels <- parseLabel(variable)
    survlist <- km.plot(as.data.frame(os.df.list[[i]]), 'Overal_survival_months',
                        'Overall_survival_censor',
                        variable,
                        paste0("Therapy ",therapy  , ": ", variable),
                        cols = c("#377EB8", "#E41A1C"))
    os.plot <-  survlist$plot
    pval <- paste0("Log rank p = ",
                   round(as.numeric(survlist$pval.logrank), 3))
    fig <- os.plot$plot +
        ylab("Overall Survival (Prob)") +
        ggtitle("") +
        scale_color_manual(values=c("#377EB8", "#E41A1C"),
                           labels=labels, name="") +
        theme(legend.direction="vertical",
              legend.position=c(0.6, 0.9),
              plot.title=element_text(hjust=0, size=20)) +
        annotate("text", x=0.1, y=0, label=pval, hjust=-2, fontface=2) +
        ggtitle(panel_label[i])
    gfig <- ggplotGrob(fig)
    tab <- os.plot$table +
        guides(color="none")
    gtab <- ggplotGrob(tab)
        scale_color_manual(values=c("#377EB8", "#E41A1C"),
                           labels=c("KRAS", "KRAS2"), name="")
    gl <- list(gfig, gtab)
    g <- arrangeGrob(grobs=gl, heights=c(1, 0.25))
    glist[[i]] <- g
}
```

```{r grobs_in_row}
L <- length(glist)
row_grobs <- arrangeGrob(grobs=glist,
                         widths=rep(1, L),
                         layout_matrix=matrix(seq_len(L),
                                              nrow=1, ncol=L))
```

```{r io_grobs}
io_grobs <- row_grobs
```


# Panels C-D: Patients recievig IO + Chemo_IO in any line of therapy

```{r survival_data_chemo_io,  echo=FALSE, include=FALSE}
## use hotspot mutations for Chromatin Reg pathway and all mutations for KEAP1, NTRK3
os <- read_tsv(here("data","os_annotated.tsv"),
               show_col_types=FALSE)
therapy_ <- therapy <- c("IO ; IO + chemo_IO", "IO + chemo_IO")
os <- os %>%
    filter(flag_KRAS_G12C == 1 ) %>%
      mutate(`KRAS_G12C~AMER1` = ifelse(flag_KRAS_G12C == 1 & flag_AMER1 == 1, 1 ,0)) %>%
      mutate(`KRAS_G12C~STK11` = ifelse(flag_KRAS_G12C == 1 & flag_STK11 == 1, 1 ,0)) %>%
    mutate(`KRAS_G12C~TP53_hotspot` = ifelse(flag_KRAS_G12C == 1 & flag_TP53_hotspot == 1, 1 ,0)) %>%
  mutate(`KRAS_G12C~PIK3CA` = ifelse(flag_KRAS_G12C == 1 & flag_PIK3CA == 1, 1 ,0)) %>%
    dplyr::rename(therapy = Survival_Analyses)


variable.list <- colnames(os)[c(81:84)]
ix <- c(grep("TP53_hotspot", variable.list),
        grep("AMER1", variable.list))
variable.list <- variable.list[ix]
parseLabel <- function(x){
    group1 <- strsplit(x, "~")[[1]][1] %>%
        str_replace("_", " ")
    group2 <- str_replace(x, "~", " / ") %>%
        str_replace("_", " ")
    labs <- c(group1, group2)
    labs
}
glist <- vector("list", 2)
panel_label <- LETTERS[3:4]

os.df <- filter(os, therapy %in% therapy_) %>%
           select(Overal_survival_months,
           Overall_survival_censor,
           COHORT_CD_DESC,
           all_of(variable.list))

os.df.list <-list(os.df , os.df)

```


```{r chemo_io}
<<surv_grobs>>
<<grobs_in_row>>
chemo_io_grobs <- row_grobs
```



# Composite graphic

```{r fig7, fig.width=10, fig.height=10, dev=c("png", "pdf")}
gl <- list(io_grobs,
           grob(), ## a little white space
           chemo_io_grobs)
grid.arrange(grobs=gl,
             widths=1,
             heights=c(1, 0.05, 1),
             layout_matrix=matrix(1:3, ncol=1))
```
