---
title: "Figure S14: gene set enrichment for triple mutants"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


```{r packages, message=FALSE}
library(tidyverse)
library(dplyr)
library(here)
library(grid)
library(gridExtra)
library(rasfuns)
##library(EnhancedVolcano)
```


```{r data_wrangling}
FIG <- 6
dat.list <- here("output", "gsea_data_wrangling.Rmd",
             "gsea_results.rds") %>%
    readRDS()
dat <- dat.list %>%
    filter(figure==FIG)

kras <- dat$kras[[1]][c(1,3,6,4)]
comutant <- dat$comutant[[1]][c(1,3,6,4)]
stats <- dat$stats[[1]][c(1,3,6,4)]
##stats2 <- dat$stats[[2]]
signif <- dat$signif[[1]][c(1,3,6,4)]
cancer <- dat$cancer[[1]][c(1,3,6,4)]
de <- dat$de[[1]][c(1,3,6,4)]
plot_titles <- paste0(kras, " / ", comutant, " co-mutant") %>%
    paste0(" vs ", kras, " mutant ", cancer)
```

```{r plot_qq}
stats2 <- map(stats, relevel_gsea_pathway)
rank.gg <- map(stats2, gg_qq)
rank.gg2 <- plot_titles %>%
    str_wrap(width=75) %>%
    map2(rank.gg, add_qq_title)
```

```{r fig_s14, fig.width=45, fig.height=50, dev=c("png", "pdf")}
grobs <- map(rank.gg2, ggplotGrob)
h <- grobs[[1]]$heights
w <- grobs[[1]]$widths
for(i in seq_along(grobs)){
    grobs[[i]]$heights <- h
    grobs[[i]]$widths <- w
}
grobs[[5]] <- nullGrob()
grid.newpage()
vp <- viewport(x=unit(0.5, "npc"),
               y=unit(0.99, "npc"),
               width=unit(0.98, "npc"),
               height=unit(0.95, "npc"),
               just=c("center", "top"))
pushViewport(vp)
grid.arrange(grobs=grobs,
             widths=c(1, 1),
             heights=c(1, 0.1, 1),
             layout_matrix=rbind(c(1, 2),
                                 5,
                                 c(3, 4)),
             newpage=FALSE)
upViewport()
vp.leg <- viewport(x=unit(0.6, "npc"),
                   y=unit(0.3, "npc"),
                   width=unit(0.7, "npc"),
                   height=unit(0.5, "npc"),
                   just="center")
pushViewport(vp.leg)
##grid.draw(leg)
upViewport()
x1 <- unit(rep(0.015, 2), "npc")
x2 <- unit(rep(0.51, 2), "npc")
y <- unit(c(0.99, 0.47), "npc")
grid.text(c("A", "C"),
          x=x1, y=y,
          gp=gpar(cex=3.5))
grid.text(LETTERS[seq(2, 4, 2)],
          x=x2, y=y,
          gp=gpar(cex=3.5))
```



grobs <- map(rank.gg, ggplotGrob)
grobs[[1]]$heights <- grobs[[2]]$heights
grobs[[1]]$widths <- grobs[[2]]$widths
grobs2 <- c(grobs, vfigs)
grobs2[[5]] <- nullGrob()
grid.newpage()
vp <- viewport(width=unit(0.98, "npc"),
               height=unit(0.98, "npc"))
pushViewport(vp)
grid.arrange(grobs=grobs2,
             widths=c(1.2, 1),
             heights=c(0.15, 1, 0.15, 1, 0.15), ## last row taller for x-axis
             layout_matrix=rbind(c(1, 5),
                                 c(1, 3),
                                 c(5, 5),
                                 c(2, 4),
                                 c(2, 5)),
             newpage=FALSE)
```
