---
title: "Figure S3: method comparison"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


```{r packages, message=FALSE}
library(tidyverse)
library(dplyr)
library(here)
library(grid)
library(gridExtra)
library(ggplot2)
##library(EnhancedVolcano)
```


```{r read_data}

# list of genes for NSCLC co-muts
glevels = c( "BRAF", "EGFR", "ERBB2", "PTEN","RB1", "TP53","KMT2D", "NF1",
                 "ATM","STK11","U2AF1","MAX","NKX2-1","AMER1","RBM10","KEAP1","NTRK3")

mlevels = c("Bayesian hierarchical","SELECT", "DISCOVER")


bayesian.dat <- here("public", "table",
             "co-mutation.Rmd","any_mutation.csv") %>%
            read_csv() %>%
            select (cancer, ras, nonras, p, mean)%>%
            mutate_if(is.numeric, round, digits=2) %>%
            filter(cancer == "non-small cell lung cancer" )%>%
            filter(ras == "KRAS_12-61")%>%
            filter(nonras %in% glevels ) %>%
            mutate(direction = ifelse(mean > 0, "CO", "ME")) %>%
            filter(p > 1.3) %>%
            mutate(method = "Bayesian hierarchical")%>%
            select(nonras, direction, method) 


discover.dat <- here("output", "methods-comparison",
                     "genie_nsclc_discover.tsv")%>%
            read_tsv() 

discover.dat <- discover.dat[c(grep("KRAS_12-61", discover.dat$gene1 ), grep("KRAS_12-61", discover.dat$gene2 )),]
discover.dat <- discover.dat[c(which(discover.dat$gene1 %in% glevels),which(discover.dat$gene2 %in% glevels)),]
discover.dat <- discover.dat  %>%
                filter(p.value < 0.05) %>%
                mutate(method = "DISCOVER")%>%
                dplyr::rename(nonras = gene1)%>%
                select(nonras, direction, method) 

select.dat <- here("output", "methods-comparison",
                     "genie_nsclc_select.tsv")%>%
            read_tsv() 

select.dat <- select.dat[c(grep("KRAS_12-61", select.dat$SFE_1 ), grep("KRAS_12-61", select.dat$SFE_2 )),]
select.dat <- select.dat[c(which(select.dat$SFE_1 %in% glevels),which(select.dat$SFE_2 %in% glevels)),]
select.dat = select.dat %>%
            filter(wMI_p.value < 0.05) %>%
            mutate(nonras = gsub("^.*- ", "", name))%>%
            mutate(method = "SELECT")%>%
            select(nonras, direction, method) 


all.dat = rbind(discover.dat, select.dat, bayesian.dat) %>%
              mutate(index = paste0(nonras, "_", method))

heatmap.dat = expand.grid(glevels, mlevels) %>%
              dplyr::rename(nonras = Var1, method  =Var2) %>%
              mutate(method = factor(method, levels = mlevels)) %>%
              mutate(nonras = factor(nonras, levels = glevels))%>%
              mutate(index = paste0(nonras, "_", method))%>%
              merge(., all.dat %>% select(index, direction), 
                      by.x = "index", by.y = "index", all.x = TRUE)%>%
              select(-index)  %>%
            mutate(direction = recode(direction, CO = "Co-occurence", 
                                      ME = "Mut.Exclusivity"))
      
```



```{r fig_s3, fig.width=20, fig.height=10, dev=c("png", "pdf")}

comut.colors <- c("#E97979","#88B5E9" )
names(comut.colors) <- c("Co-occurence", ME = "Mut.Exclusivity")

heatmap.dat %>%
  ggplot(aes(nonras ,method), color = "black") +
  geom_tile(aes(fill = direction), width = 0.9, height = 0.95) +
  scale_fill_manual(values = comut.colors, na.value = 'gray83')+
  theme_minimal(base_size=15) +
  theme(axis.ticks.x = element_blank(),
        plot.margin = margin(1,0,1,0, "cm"),
        axis.text.y = element_text(size=12),
        axis.text.x = element_text(size=12,
                                   angle =60, hjust=1),
        axis.title = element_text(size = 12),
        panel.grid = element_blank(),
        strip.text.y=element_text(size=20, angle=60, hjust=0),
        strip.text.x=element_blank(),
        strip.background=element_blank(),
        legend.title = element_blank(),
        legend.text=element_text(size=12),
        plot.title=element_text(size=12, hjust=0.5)) +
  xlab("Non-RAS Gene") +
  ylab("Method") +
  ggtitle("Co-occurence/Mutual exclusivity with KRAS Codons 12,13,and 61")


```


