---
title: "Methods comparison"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


```{r packages, message=FALSE}
library(here)
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(grid)
library(gridExtra)
```

```{r analytic_results}
chi2dir <- here("output", "chi_square.Rmd")
bayesdir <- here("output", "bayesian_model_results.Rmd")
datdir <- here("output", "simulation.Rmd")
fexact.chisq <- chi2dir %>%
    file.path("chisq_summary.rds") %>%
    readRDS()
label_model <- function(model){
    models <- c("Mutually\nexclusive", "Independent")
    dat <- tibble(model=model)
    models2 <- dat %>%
        mutate(model=case_when(model=="weighted average"~models[1],
                               model=="independent"~models[2])) %>%
        pull(model)
    factor(models2, models)
}
label_analysis <- function(analysis){
    analyses <- c("Bayesian hierarchical\nmodel", "Chi square",
                  "Fisher exact")
    dat <- tibble(analysis=analysis)
    x <- dat %>%
        mutate(analysis=case_when(analysis=="bayesian"~analyses[1],
                                  analysis=="chisq"~analyses[2],
                                  TRUE~analysis)) %>%
        pull(analysis)
    factor(x, analyses)
}
bayes <- bayesdir %>%
    file.path("bayesian_model_summary.rds") %>%
    readRDS() %>%
    mutate(number_bounded=number_simulations) %>%
    rename(n_patients=n_patients_simulated)
egfr <- readRDS(file.path(datdir, "mutual_exclusivity.rds"))
genie <- egfr[["nonras"]]
```


## Proportion correct

The size of the intervals for the fraction of simulations covering the true value also reflects the number of simulations where the interval was bounded.  Non-bounded intervals were excluded.

```{r compute_intervals}
lower_bound <- function(y, n) qbeta(0.025, y+1, n-y+1)
upper_bound <- function(y, n) qbeta(0.975, y+1, n-y+1)
posterior_median <- function(y, n) qbeta(0.5, y+1, n-y+1)
combined <- bind_rows(bayes, fexact.chisq) %>%
    mutate(analysis=label_analysis(analysis)) %>%
    mutate(p=proportion_correct,
           number_correct=as.integer(p*number_bounded),
           lower=lower_bound(number_correct, number_bounded),
           upper=upper_bound(number_correct, number_bounded),
           median=posterior_median(number_correct, number_bounded)) %>%
    mutate(x=n_patients+runif(nrow(.), -10, 10)) %>%
    mutate(n_patients=factor(n_patients)) %>%
    mutate(sd.lambda=recode_factor(sd.lambda,
                                   `0.1`= "sigma==0.1",
                                   `0.2`= "sigma==0.2",
                                   `0.5`= "sigma==0.5"),
           model=label_model(model))
```

## Average width of 95% interval

```{r summarize_ci_width}
bayes <- bayesdir %>%
    file.path("bayesian_model_results.rds") %>%
    readRDS() %>%
    group_by(model, sd.lambda) %>%
    ##summarize(ci_width=sd(ci_width), .groups="drop")
    summarize(mean_ci_width=mean(ci_width),
              median_ci_width=median(ci_width),
              n_patients=unique(n_patients_simulated),
              q1=quantile(ci_width, 0.25),
              q3=quantile(ci_width, 0.75),
              .groups="drop") %>%
    mutate(analysis="Bayesian hierarchical\nmodel")
combined2 <- bind_rows(bayes,
                       select(fexact.chisq, colnames(bayes))) %>%
    mutate(sd.lambda=recode_factor(sd.lambda,
                                   `0.1`= "sigma==0.1",
                                   `0.2`= "sigma==0.2",
                                   `0.5`= "sigma==0.5")) %>%
    mutate(n_patients=factor(n_patients)) %>%
    mutate(analysis=label_analysis(analysis),
           model=label_model(model))
```


```{r ci_width, fig.width=10, fig.height=6, dev=c("png", "pdf")}
B <- combined2 %>%
    ggplot(aes(n_patients, median_ci_width,
               color=analysis)) +
    geom_point(size=2, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=q1, ymax=q3),
                  position=position_dodge(width=0.5),
                  width=0.2) +
    theme_bw(base_size=15) +
    facet_grid(model~sd.lambda,
               labeller=labeller(sd.lambda=label_parsed)) +
    theme(strip.background=element_blank(),
          panel.grid=element_blank(),
          strip.text.y=element_text(angle=0, hjust=0),
          legend.position="bottom") +
    xlab("Number of patients") +
    ylab("Width of 95%\n confidence interval") +
    scale_y_log10() +
    guides(color=guide_legend(title=""))
leg <- cowplot::get_legend(B)
```


# Faceting rows

```{r}
statistics <- c("Proportion of \nconfidence intervals\nspanning the\ntrue odds ratio\n(Proportion, 95% credible interval)",
                "Width of 95%\nconfidence interval\n(median, IQR)")
me.proportion <- filter(combined, model=="Mutually\nexclusive") %>%
    select(n_patients, sd.lambda, analysis, median, lower, upper) %>%
    mutate(statistic=statistics[1])
me.widths <- filter(combined2, model=="Mutually\nexclusive") %>%
    select(n_patients, sd.lambda, analysis,
           median_ci_width, q1, q3) %>%
    rename(median=median_ci_width,
           lower=q1, upper=q3) %>%
    mutate(statistic=statistics[2])
me <- bind_rows(me.proportion, me.widths) %>%
    mutate(statistic=factor(statistic, statistics))
```

```{r me_fig}
titles <- c("A", "B")
C <- me %>%
    ggplot(aes(n_patients, median,
               color=analysis)) +
    geom_point(size=2, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=lower, ymax=upper),
                  position=position_dodge(width=0.5),
                  width=0.2) +
    theme_bw(base_size=15) +
    facet_grid(statistic~sd.lambda,
               labeller=labeller(sd.lambda=label_parsed),
               scales="free_y") +
    theme(strip.background=element_blank(),
          panel.grid=element_blank(),
          strip.text.y=element_text(angle=0, hjust=0),
          legend.position="bottom") +
    xlab("Number of patients") + ylab("") +
    guides(color=guide_legend(title="Statistical model")) +
    ggtitle(titles[1])
```

```{r independence}
ind.proportion <- filter(combined, model=="Independent") %>%
    select(n_patients, sd.lambda, analysis, median, lower, upper) %>%
    mutate(statistic=statistics[1])
ind.widths <- filter(combined2, model=="Independent") %>%
    select(n_patients, sd.lambda, analysis,
           median_ci_width, q1, q3) %>%
    rename(median=median_ci_width,
           lower=q1, upper=q3) %>%
    mutate(statistic=statistics[2])
ind <- bind_rows(ind.proportion, ind.widths) %>%
    mutate(statistic=factor(statistic, statistics))
```

```{r ind_fig}
D <- ind %>%
    ggplot(aes(n_patients, median,
               color=analysis)) +
    geom_point(size=2, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(ymin=lower, ymax=upper),
                  position=position_dodge(width=0.5),
                  width=0.2) +
    theme_bw(base_size=15) +
    facet_grid(statistic~sd.lambda,
               labeller=labeller(sd.lambda=label_parsed),
               scales="free_y") +
    theme(strip.background=element_blank(),
          panel.grid=element_blank(),
          strip.text.y=element_text(angle=0, hjust=0),
          legend.position="bottom") +
    xlab("Number of patients") + ylab("") +
    guides(color=guide_legend(title="Statistical model")) +
    ggtitle(titles[2])
```


```{r fig_s2, fig.width=10, fig.height=10, dev=c("png", "pdf")}
C <- C+guides(color="none")
D <- D+guides(color="none")
Cg <- ggplotGrob(C)
Dg <- ggplotGrob(D)
gl <- list(leg, Cg, Dg, nullGrob())
m <- matrix(c(1, 2, 4, 3), nrow=4)
h <- c(0.2, 1, 0.1, 1)
grid.arrange(grobs=gl,
             layout_matrix=m,
             heights=h)
```
