---
title: "Table S6: Prevalence at codons 12,13 and 61 stratified by age, sex and tumor type"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r packages, message=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(autodep = TRUE, echo=FALSE)
library(magrittr)
library(tidyverse)
library(gt)
library(here)
library(DT)
```

```{r data}
cancerlabs <- read_csv(here("data", "cancer_labels.csv"),
                       show_col_types=FALSE)
glevels  <- c("RAS", "KRAS", "HRAS", "NRAS")
clevels <- c("Age", "Race", "Sex", "Tumor type")
dat <- here("output", "prevalence",
               "summarize_models.R",
               "models.rds") %>%
    readRDS() %>%
    filter(!confounder %in% c(" ", "Center")) %>%
    unnest("data") %>%
    ungroup() %>%
    left_join(cancerlabs, by="cancer") %>%
    mutate(cancer=cancer_label) %>%
    select(hugo_symbol, codon, cancer, confounder, variable,
           y, n, mean, median, q1, q2) %>%
    mutate(hugo_symbol=factor(hugo_symbol, glevels),
           confounder=factor(confounder, clevels)) %>%
    arrange(hugo_symbol, confounder) %>%
    select(-confounder) %>%
    mutate(codon=str_replace_all(codon, "Codon ", "")) %>%
    mutate(codon=str_replace_all(codon, "^12$", "G12"),
           codon=str_replace_all(codon, "^13", "G13"),
           codon=str_replace_all(codon, "^61", "Q61")) %>%
    set_colnames(c("HUGO symbol", "Codon", "Cancer type",
                   "Group", "Variants (n)", "Patients (n)",
                   "Mean", "Median", "2.5%", "97.5%"))
```

```{r table_s6}
dat %>%
    datatable(extensions = 'Buttons',
              options = list(dom = 'Blfrtip',
                             buttons = c('copy', 'csv', 'excel',
                                         'pdf', 'print'),
                             lengthMenu = list(c(50,100,-1),
                                               c(50,100,"All"))))
```
