---
title: "Table S17. Gene sets utilized to assign individual genes in pathways and gene families."
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r packages, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(autodep = TRUE, echo=FALSE)
library(magrittr)
library(tidyverse)
library(gt)
library(here)
library(DT)
```



```{r data,  message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
extdir <- system.file("extdata", package="genie.6.1")
gene_pathways <- read_csv(file.path(extdir, "ras_pathways.csv"))


dat <- as.data.frame(gene_pathways) %>%
   dplyr::rename('HUGO symbol' = hugo_symbol,
                 'Pathway' = pathway)

```


```{r table_s17, warning=FALSE}
dat %>%
    datatable(extensions = 'Buttons',
              options = list(dom = 'Blfrtip',
                             buttons = c('copy', 'csv', 'excel',
                                         'pdf', 'print'),
                             lengthMenu = list(c(50,100,200,-1),
                                               c(50,100,200,"All"))))

```
