---
title: "Table S22.  Gene set enrichement analyses for double KRAS/non-RAS mutant vs KRAS only mutant lung adenocarcinomas."
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r packages, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(autodep = TRUE, echo=FALSE)
library(magrittr)
library(tidyverse)
library(gt)
library(here)
library(DT)
```



```{r data,  message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}

dat <- here("output", "gsea_data_wrangling.Rmd", "gsea_master_table.rds") %>%
            readRDS() %>%
            filter(Cancer == "LUAD")

```


```{r table_s22, warning=FALSE}

dat %>%
    datatable(extensions = 'Buttons',
              options = list(dom = 'Blfrtip',
                             buttons = c('copy', 'csv', 'excel',
                                         'pdf', 'print'),
                             lengthMenu = list(c(50,100,200,-1),
                                               c(50,100,200,"All"))))


```
