---
title: "Table S15. Co-occurrence of RAS mutant alleles with non-RAS gene mutations stratified by age, race, sex and tumor type."
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r packages, message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(autodep = TRUE, echo=FALSE)
library(magrittr)
library(tidyverse)
library(gt)
library(here)
```



```{r data,  message=FALSE, warning=FALSE, echo=FALSE, include=FALSE}
comut.allele.age <- read_csv(here("public", "table", "co_mutation_allele.Rmd", "any_mutation_agecat.csv"))%>% 
                  mutate(variable = paste0( variable, "yrs")) %>%
                  mutate(variable = recode(variable, "overallyrs" = "Age:overall" ))


comut.allele.race <- read_csv(here("public", "table", "co_mutation_allele.Rmd", "any_mutation_race.csv"))%>% 
                  mutate(variable = recode(variable, "Other" = "Race:Other",
                                                       "Undefined"="Race:Undefined", 
                                           "overall" = "Race:overall" ))


comut.allele.sex <- read_csv(here("public", "table", "co_mutation_allele.Rmd", "any_mutation_sex.csv"))%>% 
                  mutate(variable = ifelse(is.na(variable), "Sex:NA", variable)) %>%
                  mutate(variable = recode(variable,"overall" = "Sex:overall" ))

comut.allele.sample <-read_csv(here("public", "table", "co_mutation_allele.Rmd", "any_mutation_sample_type.csv"))%>% 
                  mutate(variable = recode(variable, "overall" = "Tumor Type:overall" ))

dat <- rbind(comut.allele.age,comut.allele.race,comut.allele.sex,comut.allele.sample ) %>%
              select (cancer, ras, nonras, number_ras, number_nonras,variable,
                      mean,"2.5%" ,"97.5%",n_eff,Rhat,
                      "00","10","01","11" ,is_driver, p)%>%
             mutate_if(is.numeric, round, digits=2) %>%
            mutate(ras = gsub("_1", "_G1", ras)) %>%
            mutate(ras = gsub("_6", "_Q6", ras)) %>%
   dplyr::rename('Cancer type' = cancer, 
                 'RAS' = ras, 
                 'Non-RAS' = nonras, 
                "RAS(n)" = number_ras, 
                 "non-RAS(n)" = number_nonras, 
                 "Group" = variable, 
                        'Mean' = mean, 
                     'Driver'= is_driver, 
                 '-log10(p)' = p)


```


```{r table_s15}
dat %>%
    gt() %>%
    tab_style(
        style = list(
            cell_text(weight = "bold")
        ),
        locations = cells_column_labels()) %>%
    cols_align(align="left", column="Cancer type")

```
